### ISSUE TITLE
Changing seat type for a class with students registered in it makes the class disappear for student

### ISSUE THREAD

**Issue by ankitamenon** [ChrisRuff/SWE4103_Project#104]
Steps to reproduce:

1. Create two student accounts, for example, student1 and stduent2. As a prof, create a class and get the two students registered. 
2. Student1 selects seat to reserve and submit 
3. Student2 selects seat to reserve and submit 
4. Log back into the prof account and change any seat type to something else and submit
5. Log back into stduent1's account and the class is no longer there, instead the no classes message is displayed

Note: the updated class is displayed when stduent2 logs in though

**Comment by mrideout1** [comment]
This is.... very strange. I will post it in Discord for people to see.
