### ISSUE TITLE
Seat type changes not saving properly in PR 87

### ISSUE THREAD

**Issue by lukesmith77** [ChrisRuff/SWE4103_Project#90]
When editing a class Layout in Professor Home, when changing seat types on click and then saving, the seat types do not save in the proper location after submit and then refresh
Reproduce:
0. Checkout bugfix-cancel-button and run project
1. Log in as a professor
2. Create a Class
3. Change some seat types, at varying depths of row and column
4. Submit then refresh, note new layout does not match what was created before the submit

**Comment by edwardchang7** [comment]
Fix for this issue is pushed in PR 87
